version: '3.8'

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
    depends_on:
      - db

  frontend1:
    build:
      context: ./frontend1
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend1:/var/www/html

  frontend2:
    build:
      context: ./frontend2
    ports:
      - "3001:80"
    depends_on:
      - backend
    volumes:
      - ./frontend2:/var/www/html

networks:
  default:
    driver: bridge